spring:
  datasource:
    username: ${app_username:darkroot}
    password: ${app_password:@darKrOot3646}
    url: jdbc:mysql://${host:localhost}:${app_port:3306}/${app_database:customer_db}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
server:
  port: 8081
  error:
    include-stacktrace: never